service: http-api
frameworkVersion: "3"
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs18.x
functions:
  Todos:
    handler: dist/app.handler
    events:
      - httpApi:
          path: /
          method: GET
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /{id}
          method: PUT
      - httpApi:
          path: /{id}
          method: DELETE
